# Titanic Data Cleaning Pipeline
Author: Rahul Prakash Mishra

Dataset: Titanic (891 rows, 12 columns)

Goal: Raw CSV in → clean, analysis-ready DataFrame out

Week 2 Law: Compression Beats Coverage

### The Inspection Ritual

In [2]:
import pandas as pd
import numpy as np

# Load
df = pd.read_csv('titanic.csv')

In [6]:
print("="*50)
print("SHAPE")
print(df.shape)

print("\nCOLUMNS")
print(df.columns.to_list())

print("\nFIRST FIVE ROWS")
print(df.head())

print("\nLAST FIVE ROWS")
print(df.tail())

print("\nDTYPES")
print(df.dtypes)

print("\nBASIC STATS")
print(df.describe())

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nMISSING VALUES PERCENTAGE")
print(df.isnull().sum()/len(df) *100)

print("\n VALUE COUNTS (Survived)")
print(df["Survived"].value_counts())

print("\n VALUE COUNTS PERCENTAGE(Survived)")
print(df["Survived"].value_counts()/len(df['Survived']) * 100)

==================================================
SHAPE
(891, 12)

COLUMNS
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

FIRST FIVE ROWS
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

LAST FIVE ROWS
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

DTYPES
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

BASIC STATS
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

MISSING VALUES
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

MISSING VALUES PERCENTAGE
PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

 VALUE COUNTS (Survived)
Survived
0    549
1    342
Name: count, dtype: int64

 VALUE COUNTS PERCENTAGE(Survived)
Survived
0    61.616162
1    38.383838
Name: count, dtype: float64

### DataFrame Selection

##### iloc: position-based (like NumPy indexing)

In [ ]:
df = pd.read_csv('titanic.csv')

array([3, 1, 2])

In [10]:
print(df.iloc[0]) # first row — returns a Series

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [11]:
print(df.iloc[0,2]) # row 0, column 2 — single value

3

In [ ]:
print(df.iloc[:5,:4]) # first 5 rows, first 4 columns

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name
0                            Braund, Mr. Owen Harris
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                           Allen, Mr. William Henry

In [13]:
df.iloc[-1] # last row

PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

##### loc: label-based (use column names)

In [ ]:
df.loc[0,'Name'] # row index 0, column 'Name'

'Braund, Mr. Owen Harris'

In [ ]:
df.loc[:4,['Name','Age','Survived']] # first 5 rows, 3 columns

                                                Name   Age  Survived
0                            Braund, Mr. Owen Harris  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                             Heikkinen, Miss. Laina  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                           Allen, Mr. William Henry  35.0         0

In [17]:
print(df.loc[df.index[-1], 'Fare'])   # last row, Fare column

# df.loc[-1, 'Fare'] it will give you error because df.loc[] uses label-based indexing, not positional indexing. this code means Find the row whose index label is -1.

7.75

##### Boolean indexing — the most important one

In [18]:
# PREDICT each output before running

survivors = df[df['Survived'] == 1]
print(survivors.shape)    # how many survived?

(342, 12)

In [22]:
# Multiple conditions — & means AND, | means OR
# NEVER use 'and' or 'or' with pandas — use & and |

young_survivors = df[(df['Survived']==1) & (df['Age']<18)]
young_survivors.shape

(61, 12)

In [33]:
first_class = df[(df['Survived']==1) & (df['Pclass']==1)]
first_class.shape

(136, 12)

In [36]:
# isin — use instead of multiple OR conditions

classes_1_and_2 = df[df['Pclass'].isin([1,2])]
classes_1_and_2.shape

(400, 12)

In [ ]:
# ~ means NOT in pandas

not_first_class = df[~df['Pclass'].isin([1])]
print(not_first_class.shape)

(675, 12)

In [ ]:
# WRONG — this will give a SettingWithCopyWarning or silent bug
survivors = df[df['Survived'] == 1]
survivors['NewCol'] = 1   # BAD

C:\Users\rahul\AppData\Local\Temp\ipykernel_27884\2320650424.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survivors['NewCol'] = 1   # BAD

In [ ]:
# RIGHT — always use .copy() when you plan to modify a slice
survivors = df[df['Survived'] == 1].copy()
survivors['NewCol'] = 1   # SAFE

### Series Operations

In [ ]:
df = pd.read_csv('titanic.csv')

In [47]:
age = df['Age']

In [49]:
print(type(age))
print(age.shape)
print(age.dtype)
print(age.mean())
print(age.std())
print(age.min(), age.max())
print(age.quantile(0.25))

<class 'pandas.core.series.Series'>
(891,)
float64
29.69911764705882
14.526497332334042
0.42 80.0
20.125

In [52]:
print(df['Pclass'].value_counts())
print(df['Sex'].value_counts())
print(df['Embarked'].value_counts(dropna=False)) # include NaN in count

Pclass
3    491
1    216
2    184
Name: count, dtype: int64
Sex
male      577
female    314
Name: count, dtype: int64
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [55]:
# unique and nunique
print(df['Embarked'].unique()) # array of unique values
print(df['Embarked'].nunique()) # count of unique values

['S' 'C' 'Q' nan]
3

In [58]:
# String operations on a Series
# df['Name'] contains strings like "Braund, Mr. Owen Harris"
df['Title'] = df['Name'].str.extract(r',\s(\w+)\.')  # extract title
print(df['Title'].value_counts())

Title
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Mlle          2
Major         2
Col           2
Don           1
Mme           1
Ms            1
Sir           1
Lady          1
Capt          1
Jonkheer      1
Name: count, dtype: int64

### dtypes and Type Conversion — Silent ML Bugs Start Here

In [60]:
df = pd.read_csv('titanic.csv')
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [63]:
# astype - convert column types

df['Survived'] = df['Survived'].astype(bool)
print(df['Survived'].dtype)
df['Survived']

bool

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889     True
890    False
Name: Survived, Length: 891, dtype: bool

In [66]:
df['Survived'] = df['Survived'].astype(int)
df['Survived'].dtype

dtype('int64')

In [ ]:
# pd.to_numeric — safer than astype when data is messy

messy_age = pd.Series(['25','30','unknown','45',None])
print(messy_age)
print(pd.to_numeric(messy_age,errors='coerce')) # errors='coerce' turns bad values into NaN instead of crashing

0         25
1         30
2    unknown
3         45
4       None
dtype: object
0    25.0
1    30.0
2     NaN
3    45.0
4     NaN
dtype: float64

In [69]:
# pd.Categorical — used for ordinal data (memory efficient + ordered)

df['Pclass'] = pd.Categorical(df['Pclass'], categories=[1,2,3], ordered=True)
print(df['Pclass'].dtype)
print(df[df['Pclass']<2])

category
     PassengerId  Survived Pclass  \
1              2         1      1
3              4         1      1
6              7         0      1
11            12         1      1
23            24         1      1
..           ...       ...    ...
871          872         1      1
872          873         0      1
879          880         1      1
887          888         1      1
889          890         1      1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
6                              McCarthy, Mr. Timothy J    male  54.0      0
11                            Bonnell, Miss. Elizabeth  female  58.0      0
23                        Sloper, Mr. William Thompson    male  28.0      0
..                                                 ...     ...   ...    ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
872                           Carlsson, Mr. Frans Olof    male  33.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch    Ticket     Fare        Cabin Embarked
1        0  PC 17599  71.2833          C85        C
3        0    113803  53.1000         C123        S
6        0     17463  51.8625          E46        S
11       0    113783  26.5500         C103        S
23       0    113788  35.5000           A6        S
..     ...       ...      ...          ...      ...
871      1     11751  52.5542          D35        S
872      0       695   5.0000  B51 B53 B55        S
879      1     11767  83.1583          C50        C
887      0    112053  30.0000          B42        S
889      0    111369  30.0000         C148        C

[216 rows x 12 columns]

In [70]:
# WHY DTYPES MATTER IN ML:
# If 'Sex' is object (string), sklearn cannot process it
# You must convert it to numeric before any model

print("\nColumns sklearn cannot use directly:")
print(df.select_dtypes(include=['object']).columns.tolist())

Columns sklearn cannot use directly:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

### Missing Value Handling

In [71]:
df = pd.read_csv('titanic.csv')

In [ ]:
# First: understand the missing data

missing_report = pd.DataFrame({
    'column': df.columns,
    'missing_count':df.isnull().sum(),
    'missing_pct': round((df.isnull().sum()/len(df) * 100),2),
    'dtype':df.dtypes
})

missing_report = missing_report[missing_report['missing_count'] > 0]
print(missing_report)

            column  missing_count  missing_pct    dtype
Age            Age            177        19.87  float64
Cabin        Cabin            687        77.10   object
Embarked  Embarked              2         0.22   object

##### THREE strategies for missing values:
###### 1. DROP — when missing % is very high (>50%) or column is irrelevant
###### 2. FILL with statistics — when missing % is low and column is numeric
###### 3. FILL with mode/constant — when column is categorical

###### Strategy 1: Drop column 'Cabin' — 77% missing, not worth it

In [78]:
df_clean = df.drop(columns=['Cabin'])
print(f"After dropping Cabin: {df_clean.shape}")

After dropping Cabin: (891, 11)

###### Strategy 2: Fill 'Age' with median (not mean — why? outliers)

In [83]:
age_median = df_clean['Age'].median()
df_clean['Age'] = df_clean['Age'].fillna(age_median)
print(f"Age nulls remaining: {df_clean['Age'].isnull().sum()}")

Age nulls remaining: 0

###### Strategy 3: Fill 'Embarked' with mode (most frequent)

In [87]:
embarked_mode = df_clean['Embarked'].mode()[0]
df_clean['Embarked'] = df_clean['Embarked'].fillna(embarked_mode)
df_clean['Embarked'].isnull().sum()

np.int64(0)

In [88]:
# Verify: no more nulls
print(f"\nTotal nulls remaining: {df_clean.isnull().sum().sum()}")

Total nulls remaining: 0

### Duplicates + String Cleaning

In [90]:
df = pd.read_csv('titanic.csv')

In [91]:
print(f"Duplicate rows: {df.duplicated().sum()}")

Duplicate rows: 0

In [92]:
print(df['PassengerId'].duplicated().sum())

0

In [93]:
df_no_dups = df.drop_duplicates()
print(f"Shape after drop_duplicates: {df_no_dups.shape}")

Shape after drop_duplicates: (891, 12)

In [94]:
df_no_dups_subset = df.drop_duplicates(subset=['Name', 'Age'])
print(f"Shape after subset dedup: {df_no_dups_subset.shape}")

Shape after subset dedup: (891, 12)

In [98]:
# String cleaning
df['Name'] = df['Name'].str.strip()
df['Sex'] = df['Sex'].str.lower()
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [99]:
# Extract title using regex — IMPORTANT: used in feature engineering
df['Title'] = df['Name'].str.extract(r',\s(\w+)\.')
print(df['Title'].value_counts())

Title
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Mlle          2
Major         2
Col           2
Don           1
Mme           1
Ms            1
Sir           1
Lady          1
Capt          1
Jonkheer      1
Name: count, dtype: int64

In [101]:
df['Title'] = df['Title'].replace(
    ['Lady', 'Countess', 'Capt', 'Col', 'Don',
     'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona', 'Ms', 'Mme', 'Mlle'], 'Rare'
)

df['Title'].value_counts()

Title
Mr        517
Miss      182
Mrs       125
Master     40
Rare       26
Name: count, dtype: int64

In [103]:
# Map string to number — basic encoding
sex_map = {'male':0, 'female':1}
df['Sex_encoded'] = df['Sex'].map(sex_map)
df[['Sex','Sex_encoded']].head()

      Sex  Sex_encoded
0    male            0
1  female            1
2  female            1
3  female            1
4    male            0

### Method Chaining

In [109]:
df_raw = pd.read_csv('titanic.csv')

In [110]:
# procedural style

df = df_raw.copy()

df = df.drop(columns=['Cabin','Ticket','PassengerId'])
df = df.dropna(subset=['Embarked'])
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Title'] = df['Name'].str.extract(r',\s(\w+)\.')
df['Title'] = df['Title'].replace(['Lady', 'Countess', 'Dr', 'Rev', 'Major',
                                    'Col', 'Capt', 'Sir', 'Jonkheer', 'Dona', 'Don'], 'Rare')
df['Sex'] = df['Sex'].map({'male':0,'female':1})
df = df.drop(columns=['Name'])
print(df.shape)

(889, 9)

In [113]:
# method chaining style

def clean_titanic(filepath: str) -> pd.DataFrame:
    """
    Full Titanic cleaning pipeline as a method chain.
    Raw CSV in -> clean DataFrame out.
    """

    return (
        pd.read_csv(filepath)
        .drop(columns=['Cabin','Ticket','PassengerId'])
        .dropna(subset=['Embarked'])
        .assign(
            Age = lambda df: df['Age'].fillna(df['Age'].median()),
            Sex = lambda df: df['Sex'].map({'male':0, 'female':1}),
            Title = lambda df: df['Name'].str.extract(r',\s(\w+)\.')[0],
            FamilySize=lambda df: df['SibSp'] + df['Parch'] + 1,
            IsAlone=lambda df: (df['SibSp'] + df['Parch'] == 0).astype(int),
        )
        .assign(
            Title=lambda df: df['Title'].replace(
                ['Lady', 'Countess', 'Dr', 'Rev', 'Major',
                 'Col', 'Capt', 'Sir', 'Jonkheer', 'Dona', 'Don'], 'Rare')
        )
        .drop(columns=['Name'])
        .reset_index(drop=True)
    )

df_clean = clean_titanic('titanic.csv')
print(df_clean.shape)
print(df_clean.head())
print(df.isnull().sum())

(889, 11)
   Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked Title  \
0         0       3    0  22.0      1      0   7.2500        S    Mr
1         1       1    1  38.0      1      0  71.2833        C   Mrs
2         1       3    1  26.0      0      0   7.9250        S  Miss
3         1       1    1  35.0      1      0  53.1000        S   Mrs
4         0       3    0  35.0      0      0   8.0500        S    Mr

   FamilySize  IsAlone
0           2        0
1           2        0
2           1        1
3           2        0
4           1        1
Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Title       1
dtype: int64

In [131]:
# pipe() — For Functions That Are Too Complex for assign()

def add_fare_bins(df: pd.DataFrame) -> pd.DataFrame:
    """Bin Fare into 4 categories"""
    df = df.copy()
    df['FareBin'] = pd.qcut(df['Fare'], q=4, labels=['Low','Mid','High','VHigh'])
    return df 

def add_age_bins(df: pd.DataFrame) -> pd.DataFrame:
    """Bin Age into child/adult/senior"""
    df['AgeBin'] = pd.cut(df['Age'],bins=[0,12,60,100],labels=['Child','Adult','Senior'])
    return df

def validate_clean(df: pd.DataFrame) -> pd.DataFrame:
    """Assert no nulls remain - fail loudly if something went wrong."""
    null_counts = df.isnull().sum()
    assert null_counts.sum() == 0,\
        f"Null Remain: {null_counts[null_counts>0]}"
    print(f"Clean DataFrame: {df.shape}, 0 nulls")
    return df

# Combine everything in one chain

df_final = (
    pd.read_csv('titanic.csv')
    .drop(columns=['Cabin','Ticket','PassengerId'])
    .dropna(subset=['Embarked'])
    .assign(
        Age = lambda df: df['Age'].fillna(df['Age'].median()),
        Title=lambda df: df['Name'].str.extract(r',\s([^\.]+)\.')[0],
        Sex=lambda df: df['Sex'].map({'male': 0, 'female': 1}),
        FamilySize=lambda df: df['SibSp'] + df['Parch'] + 1,
        IsAlone=lambda df: (df['SibSp'] + df['Parch'] == 0).astype(int),
    )
    .drop(columns=['Name'])
    .pipe(add_fare_bins)
    .pipe(add_age_bins)
    .pipe(validate_clean)
    .reset_index(drop=True)
)

print(df_final.dtypes)
print(df_final.head())

Clean DataFrame: (889, 13), 0 nulls
Survived         int64
Pclass           int64
Sex              int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked        object
Title           object
FamilySize       int64
IsAlone          int64
FareBin       category
AgeBin        category
dtype: object
   Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked Title  \
0         0       3    0  22.0      1      0   7.2500        S    Mr
1         1       1    1  38.0      1      0  71.2833        C   Mrs
2         1       3    1  26.0      0      0   7.9250        S  Miss
3         1       1    1  35.0      1      0  53.1000        S   Mrs
4         0       3    0  35.0      0      0   8.0500        S    Mr

   FamilySize  IsAlone FareBin AgeBin
0           2        0     Low  Adult
1           2        0   VHigh  Adult
2           1        1     Mid  Adult
3           2        0   VHigh  Adult
4           1        1     Mid  Adult